### ISSUE TITLE
carrierAcceptanceLocation

### ISSUE THREAD

**Issue by sherifanwar80** [FIATA/eFBL#13]
Hello,
How to get the id for carrierAcceptanceLocation
I think it comes from I think it come from United Nations Location Code (UNLOCODE) or GS1 Global Location Number (GLN).
Would you please confirm.
Thanks,
Sherif

**Comment by gdepourtales** [comment]
Hi

UNLOCODE is to be used if the carrierAcceptanceLocation involves locations where Customs clearance of goods can take place

GS1 Global Location Number is to be used for other locations. We will extend the schema with an identfierType to mabage this for all locations and improve the documentation accordingly.

Thanks

**Comment by sherifanwar80** [comment]
Thanks
